### ISSUE TITLE
File.exists? is depreciated from Ruby < v3.1.0. Please update it for compatibility

### ISSUE THREAD

**Issue by rtirkeyDiligent** [rails/builder#22]

**Comment by p8** [comment]
Hi @rtirkeyDiligent.
Do want to create a PR to fix this?
https://github.com/tenderlove/builder/blob/b3941919becdce4021a3f70838240442f155f268/rakelib/tags.rake#L17

**Comment by rtirkeyDiligent** [comment]
The Ruby version >v3.1.0 doesn't support 'File.exists?>' method and it's depreciated. It would be need to be updated.
if you can then please update it. The current method is **'File.exist?'**

**Comment by p8** [comment]
@rtirkeyDiligent I see you already fixed this on your fork. Can you upstream the change to this repo? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
